### ISSUE TITLE
模块区域可以不做选中机制，而是浮动显示按钮

### ISSUE THREAD

**Issue by crackxia** [xksoft/xky#2]
![image](https://user-images.githubusercontent.com/516438/57833043-b3daed80-77eb-11e9-8820-993210e5216f.png)
这个区域选中貌似没什么意义

可以做成鼠标经过时显示控制按钮  例如 运行 停止

现在双击运行有点反人类

**Comment by xiakexiaoyi** [comment]
阔以

**Comment by xiakexiaoyi** [comment]
已实现
